name: Dependabot auto-merge
on: pull_request_target
permissions:
  pull-requests: write
  contents: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        safe-dependency:
        - "@ember/test-helpers"
        - "@ilios/ember-template-lint-plugin"
        - "@sentry/ember"
        - "babel-eslint"
        - "browserslist"
        - "caniuse-db"
        - "dotenv"
        - "ember-a11y-testing"
        - "ember-cli-dependency-checker"
        - "ember-cli-dependency-lint"
        - "ember-cli-deprecation-workflow"
        - "ember-noscript"
        - "ember-qunit"
        - "ember-qunit-nice-errors"
        - "ember-template-lint"
        - "eslint"
        - "eslint-config-prettier"
        - "eslint-plugin-ember"
        - "eslint-plugin-node"
        - "eslint-plugin-prettier"
        - "prettier"
        - "qunit"
        - "qunit-dom"
        - "stylelint"
        - "stylelint-config-recommended-scss"
        - "stylelint-scss"
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, matrix.safe-dependency)}}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
