name: Release Notes

on: 
  push:
    tags:
    - '*'

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get Previous Tag
      id: previousTag
      run: |
        PREVIOUS_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
        echo ${PREVIOUS_TAG}
        echo ::set-output name=tag::${PREVIOUS_TAG}
    - name: Get New Tag
      id: nextTag
      run: |
        NEW_TAG=${GITHUB_REF#refs/tags/}
        echo ${NEW_TAG}
        echo ::set-output name=tag::${NEW_TAG}
    - uses: actions/setup-node@v3
    - name: Generate Release Notes
      id: notes
      run: |
        NOTES=$(npx generate-github-release-notes ilios frontend ${{ steps.previousTag.outputs.tag }} ${{steps.nextTag.outputs.tag}})
        echo ${NOTES}
        # remove line breaks from notes so they can be passed around
        NOTES="${NOTES//$'\n'/'%0A'}"
        echo "::set-output name=releaseNotes::$NOTES"
    - name: Generate Release Name
      id: name
      run: |
        NAME=$(npx dartajax-music random-song)
        echo ${NAME}
        echo "::set-output name=releaseName::$NAME"
    - uses: ncipollo/release-action@v1
      with:
        name: ${{steps.name.outputs.releaseName}}
        body: ${{steps.notes.outputs.releaseNotes}}
        token: ${{ secrets.ZORGBORT_TOKEN }}